app_web:
    resource: '@WoolfBundle/Controller/'
    type: annotation

app_api:
    resource: '@WoolfBundle/Controller/Api'
    type: annotation

app.swagger_ui:
    path: /api/doc
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
