<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerLtebcwc\appProdProjectContainer::class, false)) {
    require __DIR__.'/ContainerLtebcwc/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\ContainerLtebcwc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLtebcwc\appProdProjectContainer();
