<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container9sgwxyq\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/Container9sgwxyq/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\Container9sgwxyq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9sgwxyq\appDevDebugProjectContainer();
